/**
 * Renders a prominent banner on every legal document page making clear
 * that the content is a draft generated by AI and has NOT been reviewed
 * by a licensed attorney. Required for our own protection — and the
 * user's — until counsel has signed off.
 *
 * Once an attorney has reviewed and approved a document, delete this
 * component from that page (or change the variant prop to 'final').
 */
export default function LegalDisclaimer({ variant = "draft" }: { variant?: "draft" | "final" }) {
  if (variant === "final") return null;
  return (
    <div className="border-warning-bd bg-warning-bg rounded-lg border p-4 text-sm">
      <p className="text-warning font-semibold">⚠ Draft — not yet reviewed by counsel</p>
      <p className="text-warning mt-1 text-xs">
        This document was generated by AI as a starting point tailored to the Arbor codebase and
        operating model. It has not been reviewed by a licensed attorney. Do not rely on it for
        binding legal effect until a qualified lawyer has reviewed and approved it. Acceptance
        recorded against this version will need to be re-collected when counsel-approved language
        replaces this draft.
      </p>
    </div>
  );
}
