#!/usr/bin/env tsx
/**
 * Generates docs/permissions.md from two sources:
 *   1. JSDoc @requiredRole tags on every exported server action across
 *      apps/web/src/app/**\/actions.ts
 *   2. RLS policy metadata extracted from supabase/migrations/*.sql
 *
 * Run:
 *   pnpm tsx scripts/generate-permissions-doc.ts
 *
 * CI use:
 *   pnpm tsx scripts/generate-permissions-doc.ts --check
 *   exits 1 if the generated file differs from what's committed (drift guard).
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, "..");
const ACTIONS_GLOB_ROOT = join(ROOT, "apps/web/src/app");
const MIGRATIONS_DIR = join(ROOT, "supabase/migrations");
const OUTPUT = join(ROOT, "docs/permissions.md");

interface ActionEntry {
  file: string;
  name: string;
  requiredRole: string;
}

interface PolicyEntry {
  table: string;
  name: string;
  command: string;
  predicate: string;
}

// ── 1. Walk apps/web/src/app for actions.ts files ────────────────────────────

function findActionsFiles(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      findActionsFiles(full, out);
    } else if (entry === "actions.ts") {
      out.push(full);
    }
  }
  return out;
}

const ACTION_RE =
  /\/\*\*[\s\S]*?@requiredRole\s+([^\s*]+)[\s\S]*?\*\/\s*export\s+async\s+function\s+(\w+)/g;

function extractActions(): ActionEntry[] {
  const files = findActionsFiles(ACTIONS_GLOB_ROOT);
  const entries: ActionEntry[] = [];
  for (const file of files) {
    const src = readFileSync(file, "utf8");
    const rel = relative(ROOT, file).replace(/\\/g, "/");
    let match: RegExpExecArray | null;
    ACTION_RE.lastIndex = 0;
    while ((match = ACTION_RE.exec(src)) !== null) {
      const role = match[1];
      const name = match[2];
      if (role && name) {
        entries.push({ file: rel, name, requiredRole: role });
      }
    }
  }
  return entries.sort((a, b) =>
    a.file === b.file ? a.name.localeCompare(b.name) : a.file.localeCompare(b.file),
  );
}

// ── 2. Parse RLS policies from migration SQL ─────────────────────────────────
// We only capture CREATE POLICY statements from the most recent migrations
// (the post-Phase-3+4 set whose policy names follow the *_manager_all,
// *_instructor_*, *_self_*, *_write, *_read, *_select conventions). Older
// policy creates that have since been dropped/replaced are ignored by virtue
// of their names not appearing in the current schema.

const POLICY_RE =
  /CREATE\s+POLICY\s+(?:"([^"]+)"|(\w+))\s+ON\s+public\.(\w+)\s+(?:AS\s+\w+\s+)?FOR\s+(\w+)([\s\S]*?)(?=;|CREATE\s+POLICY|DROP\s+POLICY|EXECUTE)/gi;

function extractPolicies(): PolicyEntry[] {
  const entries: PolicyEntry[] = [];
  const seen = new Set<string>();
  // Read in reverse chronological so the latest CREATE POLICY for a given
  // (table, name) wins. Migration filenames sort lexicographically by date.
  const files = readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith(".sql"))
    .sort()
    .reverse();
  for (const f of files) {
    const src = readFileSync(join(MIGRATIONS_DIR, f), "utf8");
    let match: RegExpExecArray | null;
    POLICY_RE.lastIndex = 0;
    while ((match = POLICY_RE.exec(src)) !== null) {
      const name = match[1] ?? match[2] ?? "";
      const table = match[3] ?? "";
      const cmd = (match[4] ?? "").toUpperCase();
      const predicate = (match[5] ?? "")
        .replace(/\s+/g, " ")
        .replace(/^\s+|\s+$/g, "")
        .slice(0, 200);
      const key = `${table}::${name}`;
      if (seen.has(key)) continue;
      seen.add(key);
      entries.push({ table, name, command: cmd, predicate });
    }
  }
  return entries.sort((a, b) =>
    a.table === b.table ? a.name.localeCompare(b.name) : a.table.localeCompare(b.table),
  );
}

// ── 3. Render markdown ──────────────────────────────────────────────────────

function render(actions: ActionEntry[], policies: PolicyEntry[]): string {
  const lines: string[] = [];
  lines.push("# Permissions Reference (generated)");
  lines.push("");
  lines.push("_Generated by `pnpm tsx scripts/generate-permissions-doc.ts`. Do not edit by hand._");
  lines.push("");
  lines.push(
    "This file is the canonical record of role gating across the app. It is built from two sources:",
  );
  lines.push("");
  lines.push(
    "1. `@requiredRole` JSDoc tags on every server action (under `apps/web/src/app/**/actions.ts`).",
  );
  lines.push("2. `CREATE POLICY` statements in `supabase/migrations/*.sql`.");
  lines.push("");
  lines.push(
    "**Note on the policies section**: this is parsed from migration files. Policies dropped via dynamic SQL (e.g. the Phase 3/4 DO blocks that introspect `pg_policies`) won't be subtracted here — they may appear as legacy entries even though the live DB has replaced them. For the authoritative current state, query `pg_policies` directly. The Phase 3 and Phase 4 migrations document the canonical post-rewrite policy names (`<table>_write`, `<table>_manager_all`, `<table>_instructor_*`, `<table>_self_*`).",
  );
  lines.push("");
  lines.push("If anything in the actions section looks wrong, fix the source and re-run.");
  lines.push("");

  // ── Server actions section ─────────────────────────────────────────────
  lines.push("## Server actions");
  lines.push("");
  lines.push(`Total annotated actions: **${actions.length}**`);
  lines.push("");
  if (actions.length === 0) {
    lines.push("_No actions tagged with `@requiredRole` yet._");
  } else {
    lines.push("| File | Action | Required role |");
    lines.push("| --- | --- | --- |");
    for (const a of actions) {
      lines.push(`| \`${a.file}\` | \`${a.name}\` | \`${a.requiredRole}\` |`);
    }
  }
  lines.push("");

  // ── RLS policies section ───────────────────────────────────────────────
  lines.push("## RLS policies (current)");
  lines.push("");
  lines.push(`Total active policies (latest definition wins): **${policies.length}**`);
  lines.push("");
  lines.push("| Table | Policy | Cmd | Predicate (truncated) |");
  lines.push("| --- | --- | --- | --- |");
  for (const p of policies) {
    const pred = p.predicate.replace(/\|/g, "\\|");
    lines.push(`| \`${p.table}\` | \`${p.name}\` | ${p.command} | \`${pred}\` |`);
  }
  lines.push("");

  return lines.join("\n");
}

// ── 4. Main ──────────────────────────────────────────────────────────────────

function main() {
  const check = process.argv.includes("--check");
  const actions = extractActions();
  const policies = extractPolicies();
  const generated = render(actions, policies);

  if (check) {
    let existing = "";
    try {
      existing = readFileSync(OUTPUT, "utf8");
    } catch {
      // file missing → drift
    }
    if (existing.replace(/\r\n/g, "\n") !== generated.replace(/\r\n/g, "\n")) {
      console.error(
        "permissions.md is out of date. Run `pnpm tsx scripts/generate-permissions-doc.ts` and commit the result.",
      );
      process.exit(1);
    }
    console.log(
      `permissions.md is up to date (${String(actions.length)} actions, ${String(policies.length)} policies).`,
    );
    return;
  }

  writeFileSync(OUTPUT, generated, "utf8");
  console.log(
    `Wrote ${OUTPUT} with ${String(actions.length)} actions + ${String(policies.length)} policies.`,
  );
}

main();
